config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homepage#index'
  resources :room_messages
  resources :rooms
  get 'rooms/:id/fetch', to: 'rooms#fetch_more', as: :fetch_more

  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_messages, dependent: :destroy, inverse_of: :room
  has_many :user_rooms
  has_many :users, through: :user_rooms

  validates :name, length: { in: 1.. 12, allow_nil: false }
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  load_and_authorize_resource :except => :create
  skip_authorize_resource :only => :fetch_more

  #They are for pagination purposes
  $limit
  $offset_counter

  def show
    $limit = 5
    @rooms = Room.all
    @user_rooms = UserRoom.all
    @room_message = RoomMessage.new room: @room
    $offset_counter = @room.room_messages.includes(:user).size - 5
    @room_messages = @room.room_messages.includes(:user).order(id: :desc).limit($limit)
    $limit += 5
  end

  def index
    @rooms = Room.all
    @user_rooms = UserRoom.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_creation_parameters)
    if @room.save
      @user_room = UserRoom.new({ user_id: current_user.id, room_id: @room.id })
      @user_room.save
      redirect_to rooms_path
      template = render_to_string partial: 'room', locals: { room: @room }
      ActionCable.server.broadcast("rooms", { id: @room.id, action: "create", name: @room.name, html: template})
    else
      render :new
    end
  end

  def update
    if @room.update(room_creation_parameters)
      redirect_to rooms_path
    else
      render :new
    end
  end

  # I have there tables that must be destroyed when deleting a room and in the method you see there are only two deletle statments,
  # but because there is an Assosiation between two i only delete one and the other automatically will be deleted
  def destroy
    if can? :destroy, @room
      ActionCable.server.broadcast("rooms", { id: @room.id, action: "destroy" })
      Room.find(params[:id]).destroy
      UserRoom.where(room_id: params[:id]).map(&:destroy)
    end
    # respond_to do |format|
      # format.html { redirect_to rooms_path }
      # format.js   { render } unless params[:room_scope] == "show"
    # end
  end

  #I made the pagination manuely by getting to the top of the chat box javascript function will call fetch_more
  #and the method uses and keep track of the required offset dependening how much the user scrolled up unitl it reachers the oldest record
  def fetch_more
    $limit += 5
    $offset_counter = ($offset_counter >= 5? $offset_counter - 5: 0)
    @room_messages = (@room.room_messages.includes(:user).order(:id).limit($limit).offset($offset_counter)).to_a.reverse()
  end

  # Helper method for finding the creator of the room.
  def find_room_creator(room)
    User.find(UserRoom.where(room_id: room.id).map(&:user_id)).pluck(:username, :email).map {|username, email| {username: username, email: email}}[0]
  end

  helper_method :find_room_creator

  protected

  def room_creation_parameters
    params.require(:room).permit(:name)
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= simple_form_for @room do |form| %>
  <%= form.input :name, required: true, minLength: 1 %>
  <%= form.submit "Save", class: 'btn btn-success' %>
  <%= link_to 'Back', rooms_path, class: "btn btn-warning" %>
<% end %>

app/views/rooms/_messages.html.erb
      <% @room_messages.reverse_each do |room_message| %>
        <div class="chat-message-container">
          <div class="messages_ids row no-gutters" value="<%= room_message.id %>">
            <div class="col-auto text-center">
              <%= room_message.user.username + ": "%>
            </div>

            <div class="col">
              <div class="message-content">
                <p class="mb-1">
                  <%= room_message.message %>
                </p>

                <div class="text-right">
                  <small>
                    <%= room_message.created_at %>
                  </small>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>

app/views/rooms/_room.html.erb
<% if room.present?%>
  <div class="row delete_room <%= room.id %>">
     <div class="row room-nav-link col-12">
        <%= link_to room.name, room_path(room), class: "nav-link col-6"%>
          <% creator = find_room_creator(room)%>
          <div class="col-2">
            <% if current_user.admin? %>
              <div class="dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
                  role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>

                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  <li><%= link_to "Delete", room_path(room), method: :delete,
                    data: { confirm: "" "Created by User Name: '#{creator[:username]}'\nEmail: '#{creator[:email]}'
                            \nAre You sure you want to delete '#{room.name}'?" },
                    remote: true, class:"dropdown-item" %></li>

                  <li><%= link_to "Edit", edit_room_path(room), class: "dropdown-item" %></li>
                 </div>
              </div>
            <% end %>
          </div>
          <p class="col-2">
          <b><%=  creator[:username] %></b> </p>
     </div>
   </div>
<% else %>
  <div class="text-muted">
    The are no rooms
  </div>
<% end %>

app/views/rooms/_rooms.html.erb
<div class="mb-3 nav flex-column">
   <%= link_to "Create a Room", new_room_path, class: "btn btn-primary" %>
</div>
<div class="row">
  <div class="col-7"> </div>
  <div class="col-4"><p><b>Owner</b></p></div>
</div>
    <% if @rooms.present? && @user_rooms.present? %>
      <nav class="nav flex-column">
        <% @rooms.each do |room| %>
          <div class="row delete_room">
            <% if can? :read, room %>
              <!-- <div id="connect" class="col&#45;11"> -->
                <div class="row room-nav-link col-12">
                  <%= link_to room.name, room_path(room), class: "nav-link col-6" %>
                  <% creator = find_room_creator(room)%>
                  <div class="col-2">
                    <% if current_user.admin? || current_user.user_rooms.where(room_id: room.id).present? %>
                      <div class="dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
                          role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                          <li><%= link_to "Delete", room_path(room), method: :delete,
                            data: { confirm: "" "Created by User Name: '#{creator[:username]}'\nEmail: '#{creator[:email]}'
                                    \nAre You sure you want to delete '#{room.name}'?" },
                            remote: true, class:"dropdown-item" %></li>

                          <li><%= link_to "Edit", edit_room_path(room), class: "dropdown-item" %></li>
                         </div>
                      </div>
                    <% end %>
                  </div>
                  <p class="col-2">
                  <b><%=  creator[:username] %></b> </p>
                </div>
              <!-- </div> -->
            <% end %>
          </div>
        <% end %>
      </nav>
    <% else %>
      <div class="text-muted">
        The are no rooms
      </div>
    <% end %>

app/views/rooms/edit.html.erb
<h1> Updateing room <%= @room.name %> </h1>
<%= render partial: 'form' %>

app/views/rooms/fetch_more.js.erb
$('.chat').html("<%= escape_javascript(render partial: 'messages') %>")

app/views/rooms/index.html.erb
<div class="container">
  <br>
  <br>
  <br>
  <br>
  <div class="row">
    <div class="col-12 col-md-3" id="room_header">
      <%= render partial: 'rooms' %>
    </div>

    <div class="col">
      <div class="alert alert-primary">
        <h4 class="alert-heading">
          Welcome to the Online Live Chat website!
        </h4>

        <p>
          We need to talk.
        </p>

        <hr />

        <p>
          You can create or join a room from the sidebar.
        </p>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<h1> Creating a Room </h1>

<%= render partial: 'form' %>

app/views/rooms/show.html.erb
<br><br><br><br><br><br>
<div class='container'>
  <h1>
      <%= "Room name: " + @room.name %>
  </h1>

  <div class="row">
    <div class="col-12 col-md-3">
      <%= render partial: 'rooms' %>
    </div>

    <div class="col">
      <div class="chat" data-channel-subscribe="room" data-room-id="<%= @room.id %>" data-url="<%= fetch_more_path %>" >
        <%= render partial: 'messages' %>
      </div>

      <%= simple_form_for @room_message, remote: true do |form| %>
        <div class="input-group mb-3">
          <%= form.input :message, as: :string,
                                   wrapper: false,
                                   label: false,
                                   input_html: {
                                     class: 'chat-input'
                                   } %>
          <div class="input-group-append">
            <%= form.submit "Send", class: 'btn btn-primary chat-input', remote: true %>
          </div>
         </div>
        <%= form.input :room_id, as: :hidden %>
      <% end %>
      <div>
        <%= link_to 'Back', rooms_path, class: "btn btn-warning btn-lg btn-block" %>
      </div>
    </div>
  </div>

  <div class="d-none" id="template" data-role="message-template">
    <div class="chat-message-container">
      <div class="row no-gutters">
      <div class="col-auto text-center">
        <p data-role="user-name"> </p>
        </div>
        <div class="col">
          <div class="message-content">
            <p class="mb-1" data-role="message-text"></p>

            <div class="text-right">
              <small data-role="message-date"></small>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>